name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      # Check out repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Adjust to your local Flutter version
          channel: 'stable'
          architecture: x64

      # Verify Flutter installation
      - name: Check Flutter version
        run: flutter --version

      # Get Flutter dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Restore Firebase config
      - name: Restore Firebase config
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > ios/Runner/GoogleService-Info.plist

      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

      # Build the APK
      - name: Build
        run: flutter build apk 
